# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SWAGGER_HUB_API: OAPI

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # Runs a script to get all the files changed in the commit or PR
      - name: Get Changed Files
        id: gh-action-get-changed-files
        # You may pin to the exact commit or the version.
        # uses: lots0logs/gh-action-get-changed-files@af14147b3aba94b0ced11732399a2ab748097de9
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          # GitHub Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}

      # - run: echo "The modified files are ${{ fromJSON(steps.gh-action-get-changed-files.outputs.all)[0] }}"
      - name: Save modified files to env var
        env:
          SWAGGER_HUB_API: ${{ fromJSON(steps.gh-action-get-changed-files.outputs.all) }}
        run: echo "$SWAGGER_HUB_API"
      # - run: echo "SWAGGER_HUB_API=${{ steps.gh-action-get-changed-files.outputs.all }}" >> $GITHUB_ENV
      # - run: echo "The first modified file taken from env variable is ${{ env.SWAGGER_HUB_API }}"
